### ISSUE TITLE
CDN link is out of date

### ISSUE THREAD

**Issue by briatte** [noniq/Markdown-MathJax.tmbundle#1]
Hi,

The bundle uses the old MathJax CDN URL, which is marked as out of date since 2017 (even though it still seems to work):

https://github.com/noniq/Markdown-MathJax.tmbundle/blob/1e7f3250c33f27ade75b5853a7e409683d3c5626/Support/append_mathjax_js#L22

The new CDN links are at https://docs.mathjax.org/en/latest/start.html#mathjax-cdn

Not sure which one would better fit.

MathJax recommends __cdnjs__, which has a version tag in the URL:

https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js

… but perhaps a 'rolling release' URL would be best?

**Comment by noniq** [comment]
Thanks for reporting this!
